name: Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install DVC
      run: pip install dvc

    - name: Set up DVC remote repository
      run: |
        dvc init
        dvc remote add origin s3://dvc
        dvc remote modify origin-s3 endpointurl https://dagshub.com/shaikasheesh/MLOPS_E2E.s3
        dvc remote modify origin-s3 --local access_key_id 54e8af5c56141dcea8d7b9399793ee2d59893c34
        dvc remote modify origin-s3 --local secret_access_key 54e8af5c56141dcea8d7b9399793ee2d59893c34
        dvc pull models

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Run tests in Docker container
      run: |
        docker run --rm my-docker-image pytest

    - name: Run linting in Docker container
      run: |
        docker run --rm my-docker-image pylint .
